name: Create GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create_pages:
    runs-on: ubuntu-latest
    container: pandoc/core:latest
    steps:
      - uses: actions/checkout@v2
      - run: find .
